Repository webpack-contrib/webpack-serve, pull requests merged in 2018-03, with the labels that each got.

#32 Use modular Lodash imports
  lib/config.js
  lib/options.js
  package.json
Labels: kind ✨ enhancement

#50 Allow Users to Completely Disable webpack-hot-client
  README.md
  cli.js
  lib/options.js
  package-lock.json
  package.json
  test/tests/cli.js
  test/tests/options.js
Labels: kind ✨ enhancement

#72 Open option fixes
  README.md
  cli.js
  lib/options.js
  lib/server.js
  package-lock.json
  package.json
  test/tests/options.js
Labels: kind ✨ enhancement, kind 🐛 bug, p¹ 🔥🔥🔥 critical

#76 Add watch-content Add-on Recipe
  docs/addons/watch-content.config.js
Labels: kind ✨ enhancement, waiting on upstream
