Repository webpack-contrib/webpack-serve, pull requests merged in 2018-05, with the labels that each got.

#133 fix: calling middleware in add should find open ports. fixes #130
  lib/server.js
Labels: kind 🐛 bug, p¹ 🔥🔥🔥 critical

#136 feat: improve event parameters
  README.md
  index.js
  lib/server.js
  test/tests/events.js
Labels: kind ✨ enhancement, p² 🔥🔥 important, v³ ⋅ major

#142 Options: If using pfx ensure a buffer is used
  lib/options.js
Labels: kind 🐛 bug, p¹ 🔥🔥🔥 critical, waiting on upstream
